name: wikibus-facts
services:
  appserver:
    type: node
    port: 12345
    command: npm run start
    overrides:
      environment:
        PORT: 12345
        BASE_URI: https://wikibus-sheets.lndo.site/
        SPARQL_ENDPOINT: http://fuseki:3030/wikibus-data-sheets/query
        SPARQL_UPDATE_ENDPOINT: http://fuseki:3030/wikibus-data-sheets/update
    moreHttpPorts:
      - 12346
  fuseki:
    type: compose
    services:
      image: blankdots/jena-fuseki:fuseki3.13.1
      command: /docker-entrypoint.sh /jena-fuseki/start-fuseki.sh
      environment:
        ADMIN_PASSWORD: password
        ENABLE_DATA_WRITE: "true"
        ENABLE_UPDATE: "true"
        ENABLE_UPLOAD: "true"
      volumes:
        - ./fuseki/config.ttl:/data/fuseki/config/config.ttl
proxy:
  appserver:
    - wikibus-sheets.lndo.site:12345
  fuseki:
    - wikibus-sheets-db.lndo.site:3030
