language: node_js
node_js: "12"

env:
  - FUSEKI_VERSION=3.12.0

before_script:
  - npm install -g wait-on
  - curl -s http://archive.apache.org/dist/jena/binaries/apache-jena-fuseki-$FUSEKI_VERSION.tar.gz | tar -xz
  - ( cd ./apache-jena-fuseki-$FUSEKI_VERSION; ./fuseki-server > /dev/null ) &
  - wait-on --timeout 30000 http://localhost:3030
  - "curl 'http://localhost:3030/$/datasets' -H \"Content-Type: application/x-www-form-urlencoded; charset=UTF-8\" --data \"wikibus-data-sheets&dbType=mem\""
  - cp .env.defaults .env
  - npm run start > /dev/null &
  - wait-on --timeout 40000 http://localhost:12345

script:
  - npm run test
