BASE <http://localhost:12345/>
PREFIX api: <https://facts.wikibus.org/api#>

CONSTRUCT
{
  <> a api:Entrypoint ;
     api:dataSheetCollection <data-sheets> .

  <data-sheets> a api:DataSheetCollection .
}
WHERE {

}
