name: Export all

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  export-annotations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - run: npm ci
      - run: npm run export
        env:
          PROJECT_ID: ${{ vars.PROJECT_ID }}
          INCEPTION_URL: ${{ vars.INCEPTION_URL }}
          AUTH: ${{ secrets.AUTH }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: data-sheets
          path: output
